version: '3.1'

services:
  timeboard_postgres:
    container_name: timeboard_postgres
    image: postgres:15.1
#    env_file:
#          - .env
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: timeboard-db

    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - "5431:5432"
    restart: always

#  timeboard_pgadmin:
#    image: dpage/pgadmin4
#    container_name: timeboard_pgadmin
#    restart: always
#    ports:
#      - "5050:80"
#    env_file:
#      - .env

volumes:
  pg_data: {}
